<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>SeerAssetExporter</AssemblyName>
    <RootNamespace>SeerAssetExporter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AssetsTools.NET">
      <HintPath>..\..\Assets\Tools\AssetsTools.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\Assets\Tools\Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>..\..\Assets\Tools\Mono.Cecil.Mdb.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>..\..\Assets\Tools\Mono.Cecil.Pdb.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>..\..\Assets\Tools\Mono.Cecil.Rocks.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
